%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(message).
-define(message, true).

-define(message_gpb_version, "4.4.0").

-ifndef('RAWMESSAGE_PB_H').
-define('RAWMESSAGE_PB_H', true).
-record('RawMessage',
        {'Channel' = 0          :: non_neg_integer() | undefined, % = 1, 32 bits
         'Publisher' = 0        :: non_neg_integer() | undefined, % = 2, 32 bits
         'Protocol' = []        :: iolist() | undefined, % = 3
         'ContentType' = []     :: iolist() | undefined, % = 4
         'Payload' = <<>>       :: iodata() | undefined % = 5
        }).
-endif.

-ifndef('MESSAGE_PB_H').
-define('MESSAGE_PB_H', true).
-record('Message',
        {'Channel' = 0          :: non_neg_integer() | undefined, % = 1, 32 bits
         'Publisher' = 0        :: non_neg_integer() | undefined, % = 2, 32 bits
         'Protocol' = []        :: iolist() | undefined, % = 3
         'Name' = []            :: iolist() | undefined, % = 4
         'Unit' = []            :: iolist() | undefined, % = 5
         'Value' = 0.0          :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         'StringValue' = []     :: iolist() | undefined, % = 7
         'BoolValue' = false    :: boolean() | 0 | 1 | undefined, % = 8
         'DataValue' = []       :: iolist() | undefined, % = 9
         'ValueSum' = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 10
         'Time' = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 11
         'UpdateTime' = 0.0     :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 12
         'Link' = []            :: iolist() | undefined % = 13
        }).
-endif.

-endif.
